### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by jeromecc** [ppazos/cabolabs-emrapp#51]
Hello!

I created an account on https://cabolabs-ehrserver.rhcloud.com, I wanted to use cabolabs-emrapp to give it a try but I couldn't get it to compile on Eclipse Oxygen with Groovy Eclipse Feature plugin (version 2.9.2 including Groovy Compiler 2.3 and 2.4).
Is there a simple how-to available to get it running on Eclipse (or through the command line) for non Groovy experts?

Should I use an earlier version of Eclipse?

Am I missing any required plugins or using wrong versions of plugin or the compiler?

Should I use SDKMAN?

Installing Stretch Debian package groovy (2.4.8-1) didn't help.

Thanks.

**Comment by ppazos** [comment]
@jeromecc the rhcould servers are being shutdown because redhat is closing that PaaS service. You'll need to install the EHRServer locally to make the EMRApp work. But I'll suggest to use the Insomnia scripts (in the EHRServer project, under the api folder) to make the commit and the openEHR-OPT project to generate the XML to be committed.

For all my Grails projects, you'll need Grails installed. SDKMAN is a tool that allows to install Grails and manage versions. It should work OK.

**Comment by jeromecc** [comment]
Ok I will give a try at installing EHRServer locally or on one of my VPS and I'll have a look at the Insomnia scripts.
I hope installing EHRServer is withing reach of someone who is not into Java that much and who was never involved in a Groovy project.
AFAIK you are the only link between openEHR and the open source community. I keep reading about how openEHR is used in closed source commercial products. Good for them. But I still haven't found any notable EHR open source project using opeEHR other than your own... I need to upgrade the data structure and databases of my own EHR (https://github.com/freehealth) so I was thinking about openEHR achetypes instead of reinventing the wheel by myself...

It's too bad that  rhcloud servers are shutting down. Having a ready to use test server is a great way to attract free software developers.

Thanks for your quick replies! :-)

**Comment by ppazos** [comment]
@jeromecc the EHRServer guide has the step by step on how to install EHRServer, installation has nothing to do with Java knowledge :)

Always refer to the guide when dealing with the EHRServer: https://www.cabolabs.com/en/products/ehrserver

I'm not sure about the community, but I'm all for openEHR and all for open source, and been part of the openEHR community since 2006 when I started to use the first Java Reference Implementation and helped to improve it. BTW that was open source more than 10 years ago!

Yep, the service I was using for the test servers was free, to create new test server will have it's costs. I believe this is needed but might need donations from the community to keep that server running.

If it's OK I'll close this issue. If you have any questions about EHRServer you can use our forum: cabolabs.com/forum
